# Generated by Django 4.1.4 on 2022-12-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("write_encode_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_key", models.CharField(max_length=50)),
                ("inputs", models.ManyToManyField(to="write_encode_app.input")),
            ],
        ),
    ]
