# Generated by Django 4.1.4 on 2023-01-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_encode_app', '0003_translation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Session',
        ),
        migrations.AddField(
            model_name='translation',
            name='output',
            field=models.TextField(default='', max_length=999999999),
        ),
        migrations.AlterField(
            model_name='input',
            name='content',
            field=models.TextField(max_length=9999, unique=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(max_length=15),
        ),
    ]
