# Generated by Django 4.1.4 on 2023-01-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_encode_app', '0004_rename_sessions_session_translation_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
