# Generated by Django 4.1.3 on 2023-01-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("write_encode_app", "0005_alter_session_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="input_content",
            field=models.TextField(default="", max_length=999999999),
        ),
        migrations.AddField(
            model_name="translation",
            name="session",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="write_encode_app.session",
            ),
        ),
        migrations.AlterField(
            model_name="input",
            name="content",
            field=models.TextField(max_length=9999),
        ),
    ]
