# Generated by Django 4.1.4 on 2023-01-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('write_encode_app', '0005_alter_session_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='write_encode_app.session'),
        ),
    ]
