# Generated by Django 4.1.4 on 2023-01-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_encode_app', '0006_translation_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='input_content',
            field=models.TextField(default='', max_length=999999999),
        ),
    ]
