# Generated by Django 4.1.4 on 2023-01-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_encode_app', '0007_translation_input_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='content',
            field=models.TextField(max_length=9999),
        ),
    ]
